<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Intanet Domesle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/sticky-footer-navbar.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/hideShowPassword.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <?= $this->headStyle(); ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
<?php if($user = $this->identity()): ?>
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tankstelle<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                             	<li><a href="<?php //echo $this->url('fueldata') ?>" onclick="$('#waitModal').modal()">Tankdaten</a></li>
                             	<li role="separator" class="divider"></li>
                             	<li><a href="<?php //echo $this->url('fuelstation') ?>" onclick="$('#waitModal').modal()">Tankstellen Verwaltung</a></li>
                             	<li role="separator" class="divider"></li>
                                <li><a href="<?php //echo $this->url('fuelreport') ?>" onclick="$('#waitModal').modal()">Mengen Verwaltung</a></li>
                           </ul>
                       </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right ">
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->escapeHtml($user->getUsername()) ?><span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                 <li><a href="<?php echo $this->url('logout') ?>">abmelden</a></li>
                           </ul>
                       </li>
                    </ul>
<?php else: ?>
					</ul>
                    <div class="nav navbar-nav navbar-right ">
                        <a class="btn btn-info navbar-btn" role="button" href="/login">Anmelden</a>
                    </div>
<?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
            <footer class="footer">
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
