<?php
//$this->headTitle('Anmelden');
use Zend\Form\Element\Captcha;
$form->get('email')
->setAttributes([
    'class' => 'form-control input-sm',
    'placeholder' => 'name@domesle.de',
    'required' => true,
    'autofocus' => true,
]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
]);

$form->prepare();
?>

<div class="row">
	<div class="col-md-offset-4 col-md-4">
		<?= $this->form()->openTag($form); ?>
		<div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
			<?= $this->formElement($form->get('email')) ?>
			<?= $this->formElementErrors($form->get('email')); ?>
		</div>
		<p>
		<div class="form-group">
		<?= $this->formElement($form->get('captcha')); ?>
		</div>
		<?= $this->formElement($form->get('csrf')); ?>
		<?= $this->formElement($form->get('submit')); ?>
			
		<?= $this->form()->closeTag();?>
    </div>
</div>
<?php 
echo $this->form()->closeTag();
 ?>