<style>
.well {
	background: rgba(254, 254, 254, 0.5)
}
</style>


<div class="well text-center">
<?php
if($id == 'sent') {?>
	<p>Eine E-Mail wurde an Ihre Adresse versandt.
	<p><a href="<?= $this->url('home') ?>">Weiter</a>
<?php 
}
if($id == 'invalid-email') {?>
	<p>Es tut uns leid, aber die angegebene E-Mail Adresse konnte nicht im System gefunden werden.
	<p><a href="<?= $this->url('home') ?>">Abbrechen </a><a href="<?= $this->url('users', ['action' => 'forgetPassword']) ?>"> Wiederholen</a>
<?php 
}
?>
</div>