<?php
$this->headTitle('Passwort zurücksetzen');

$form->get('password')->setAttributes([
	'class'=>'form-control input-sm',
	'id' => 'password'
]);

$form->get('confirm_password')->setAttributes([
	'class'=>'form-control input-sm',
	'id' => 'confirm-password'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-6">
   		<?= $this->form()->openTag($form); ?>
   		<div class="form-group">
       	    <?= $this->formLabel($form->get('password')); ?>
           	<?= $this->formElement($form->get('password')); ?>
           	<?= $this->formElementErrors($form->get('password')); ?>
		</div>
		<div class="form-group">
           	<?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
   	        <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
     	</div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
   	</div>
</div>  
<script>
$('#password').hidePassword(true);
$('#confirm-password').hidePassword(true);
$('#password')
	.on('passwordShown', function(){
		$('#confirm-password').showPassword(true);
	})
	.on('passwordHidden', function(){
		$('#confirm-password').hidePassword(true);
	})
$('#confirm-password')
	.on('passwordShown', function(){
		$('#password').showPassword(true);
	})
	.on('passwordHidden', function(){
		$('#password').hidePassword(true);
	});		
</script>
